<LINK href="includes/imageslider.css" type=text/css rel=stylesheet>
<SCRIPT language="javascript" src="includes/imageslider.js"></SCRIPT>

<script language="JavaScript">
/* JAVASCRIPT IMAGE SLIDER */
/* CISlider1(['http://rodrigo/3xcam/modelos/8/hp_mod8.jpg','http://www.usingit.com/products/webapps/image_scroller/jsimagescroller/index.html','_self','This script was generated by JavaScript Image Slider from usingit.com',275,260]); */
<%=impSlideModelos("M")%>

function CISlider1(ipa){
if(!(window.Slider1cfg)){eval('window.Slider1cfg=new Array();');};
Slider1cfg[Slider1cfg.length]=ipa;};
function InitSlider1(){
if (!window.Bmaf){setTimeout('InitSlider1()',350);return;};
new BXae('Slider1_div',180,270,1,39,0,0,'111111',Slider1cfg,4,4);};
InitSlider1();

</script>


<DIV id=Slider1_div style="WIDTH: 180px; HEIGHT: 270px"></DIV>


<%
Function impSlideModelos(origem)

	DIM aModelos, temp, ind, strInd, intTotal
	DIM strControle, qtModelo
	
	if uCase(trim(origem)) = "M" then
		qtModelo	= 30
	else
		qtModelo	= 30
	end if
	
	'===== MODELOS =====
	sSQL = "SELECT	modelo, nomeArquivo, dataCadastro " & _
			"FROM	XCA_modelos " & _
			"WHERE	status = 'A' " & _
			"ORDER BY dataCadastro DESC"
			
	aModelos	= getArray(sSQL)
	if isArray(aModelos) then
	
		intTotal = cInt(uBound(aModelos, 2))
		if intTotal > qtModelo then
			intTotal = qtModelo
		end if
	
		for i = 0 to intTotal
		
			Randomize
			ind = cInt(RND * UBound(aModelos,2))
			
			while inStr(strControle, "("&ind&")")
			
				Randomize
				ind = cInt(RND * UBound(aModelos,2))
			
			wend
			
			strControle = strControle & " (" & ind & ") "
			
			temp =	temp &	"CISlider1(['modelos/" & aModelos(0,ind) & "/" & aModelos(1,ind) & "','modelos.asp?modelo=" & aModelos(0,ind) & "','_self','Imagem das modelos',275,260]);" & vbcrlf
	
		next
	end if
	
	impSlideModelos = temp

End Function
%>